package https.courses_fit_cvut_cz.ni_am1.hw.web_services;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.4.2
 * 2022-11-20T11:43:18.803+01:00
 * Generated source version: 3.4.2
 *
 */
@WebService(targetNamespace = "https://courses.fit.cvut.cz/NI-AM1/hw/web-services/", name = "CardPort")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface CardPort {

    @WebMethod
    @WebResult(name = "validateCardResponse", targetNamespace = "https://courses.fit.cvut.cz/NI-AM1/hw/web-services/", partName = "validateCardResponse")
    public ValidateCardResponse validateCard(

        @WebParam(partName = "validateCardRequest", name = "validateCardRequest", targetNamespace = "https://courses.fit.cvut.cz/NI-AM1/hw/web-services/")
        ValidateCardRequest validateCardRequest
    );
}
