# Generated by Django 4.1.3 on 2022-12-02 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                ("country_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=60)),
                ("code", models.CharField(max_length=2)),
            ],
            options={
                "db_table": "country",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                ("customer_id", models.AutoField(primary_key=True, serialize=False)),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("identification_number", models.CharField(max_length=20)),
            ],
            options={
                "db_table": "customer",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                ("location_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
                ("street", models.CharField(max_length=150)),
                ("city", models.CharField(max_length=50)),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING, to="api.country"
                    ),
                ),
            ],
            options={
                "db_table": "location",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Tour",
            fields=[
                ("tour_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="api.location",
                    ),
                ),
            ],
            options={
                "db_table": "tour",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="CustomerOnTour",
            fields=[
                (
                    "customer_on_tour_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.customer"
                    ),
                ),
                (
                    "tour",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.tour"
                    ),
                ),
            ],
        ),
    ]
