# Generated by Django 4.1.3 on 2022-12-04 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_customerontour_date_end_customerontour_date_start"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customerontour",
            options={"managed": True},
        ),
        migrations.AlterModelTable(
            name="customerontour",
            table="customer_on_tour",
        ),
    ]
